//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 15/11/11.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

//// In trial version of PaintCode, the code generation is limited to one canvas

// Drawing Methods
+ (void)drawCanvas2WithFrame: (CGRect)frame value: (CGFloat)value;



@end
